logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE
    org.exampledriven: DEBUG

post-service:
  url: https://jsonplaceholder.typicode.com/posts?userId={userId}

spring:
  cache:
    jcache:
      config: ehcache3.xml